sudo: false

services:
  - docker

language: bash

before_install:
  - docker -v

script:
  - docker build -t "appium/appium:latest" -f Appium/Dockerfile .
  - docker run --rm -v $PWD/Appium/tests:/root/tests "appium/appium:latest" bash tests/run-bats.sh

after_success:
  - if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ "$TRAVIS_TAG" != "" ]]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker tag "appium/appium:latest" "appium/appium:$TRAVIS_TAG" && docker push "appium/appium:$TRAVIS_TAG" ;
    fi

  - if [[ $TRAVIS_BRANCH == 'master' ]] && [[ $TRAVIS_PULL_REQUEST == "false" ]]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker tag "appium/appium:latest" "appium/appium:latest" && docker push "appium/appium:latest" ;
    fi

  - if [[ $TRAVIS_PULL_REQUEST == "true" ]]; then
    docker images;
    fi
